pipeline{
   agent {
       label 'master'
   }
   tools {
       maven 'maven3'
       jdk 'jdk11'
   }

  stages{

    stage('Validate the code'){
          steps {
              script {
              sh """
               echo 'THis is demo project'
               mvn validate
              """
              }
        
          }
      }
    stage('Code Compile'){
          steps {
             
            sh 'mvn compile'
        
          }
      }
    stage('Run test cases'){
          steps {
             
              sh 'mvn test'
        
          }
      }
    stage('Create Package'){
          steps {
             
              sh 'mvn package'
        
          }
      }
  }

}
